# appveyor.yml
#version: 0.1.0
image: Visual Studio 2019

# Установка зависимостей
install:
  - pip install -r requirements.txt


# Этап сборки
build_script:
  - python -m unittest discover  # Выполните тесты, если они у вас есть
  
after_build:
  - ps: Invoke-RestMethod -Uri "https://api.render.com/deploy/srv-cruhsitumphs73ennfh0?key=Wzrx5Xrj5dk" -Method Post
